/**
 * SFWbrowse - Monorepo Core Synchronization Pipeline
 *
 * Compiles declarative rule catalogs into ESM data modules and fans out
 * core runtime modules, unit tests, and UI components from sfwbrowse-core
 * into browser distribution ports (sfwbrowse-chrome, sfwbrowse-firefox, sfwbrowse-safari).
 */

import { mkdir, readFile, writeFile, copyFile, access } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const monorepoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(monorepoRoot, "..");
const coreDir = resolve(monorepoRoot, "core");

async function fileExists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function sync() {
  console.log("Starting SFWbrowse core synchronization...");

  // 1. Compile declarative JSON files into pure JS data module
  const cookiesJsonPath = resolve(coreDir, "rules/cookies.json");
  const blocklistJsonPath = resolve(coreDir, "rules/blocklist.json");
  const safesearchJsonPath = resolve(coreDir, "rules/safesearch-rules.json");

  const cookieRules = (await fileExists(cookiesJsonPath))
    ? await readFile(cookiesJsonPath, "utf8")
    : "[]";
  const blocklistRules = (await fileExists(blocklistJsonPath))
    ? await readFile(blocklistJsonPath, "utf8")
    : "{}";
  const safesearchRules = (await fileExists(safesearchJsonPath))
    ? await readFile(safesearchJsonPath, "utf8")
    : "[]";

  const rulesData =
    "// Auto-generated by scripts/sync-core.mjs - DO NOT EDIT DIRECTLY\n" +
    `export const COOKIE_RULES = ${JSON.stringify(JSON.parse(cookieRules), null, 2)};\n` +
    `export const BLOCKLIST_RULES = ${JSON.stringify(JSON.parse(blocklistRules), null, 2)};\n` +
    `export const SAFESEARCH_RULES = ${JSON.stringify(JSON.parse(safesearchRules), null, 2)};\n`;

  await writeFile(resolve(coreDir, "rules-data.js"), rulesData);
  console.log("✓ Compiled rules/ into core/rules-data.js");

  // 2. Synchronize to Chrome, Firefox, and Safari ports
  const ports = ["sfwbrowse-chrome", "sfwbrowse-firefox", "sfwbrowse-safari"];
  const sharedCoreFiles = [
    "storage.js",
    "enabled-state.js",
    "site-settings.js",
    "redirect-guard.js",
    "cookies-mode.js",
    "content-troddit.js",
    "blocklist.js",
    "rules-data.js",
    "blocked.html",
    "blocked.css",
    "blocked.js",
    "storage.test.js",
    "enabled-state.test.js",
    "site-settings.test.js",
    "redirect-guard.test.js",
    "cookies-mode.test.js",
    "content-troddit.test.js",
    "blocklist.test.js",
  ];

  for (const port of ports) {
    const destPortRoot = resolve(workspaceRoot, port);
    const destSrc = resolve(destPortRoot, "src");
    const destPopup = resolve(destPortRoot, "popup");
    const destOptions = resolve(destPortRoot, "options");
    const destRules = resolve(destPortRoot, "rules");

    await mkdir(destSrc, { recursive: true });
    await mkdir(destPopup, { recursive: true });
    await mkdir(destOptions, { recursive: true });
    await mkdir(destRules, { recursive: true });

    // Copy shared source modules and test suites
    for (const file of sharedCoreFiles) {
      const srcPath = resolve(coreDir, file);
      if (await fileExists(srcPath)) {
        await copyFile(srcPath, resolve(destSrc, file));
      }
    }

    // Copy storage to popup directory
    if (await fileExists(resolve(coreDir, "storage.js"))) {
      await copyFile(resolve(coreDir, "storage.js"), resolve(destPopup, "storage.js"));
    }

    // Copy options page UI
    const optionsFiles = ["options.html", "options.css", "options.js", "storage.js"];
    for (const file of optionsFiles) {
      const srcPath = resolve(coreDir, file);
      if (await fileExists(srcPath)) {
        await copyFile(srcPath, resolve(destOptions, file));
      }
    }

    // Copy static rulesets for declarativeNetRequest
    if (await fileExists(safesearchJsonPath)) {
      await copyFile(safesearchJsonPath, resolve(destRules, "safesearch-rules.json"));
    }
    if (await fileExists(blocklistJsonPath)) {
      await copyFile(blocklistJsonPath, resolve(destRules, "blocklist.json"));
    }

    // Copy blocked splash to port root for direct extensionPath access
    for (const splashFile of ["blocked.html", "blocked.css", "blocked.js"]) {
      const splashPath = resolve(coreDir, splashFile);
      if (await fileExists(splashPath)) {
        await copyFile(splashPath, resolve(destPortRoot, splashFile));
      }
    }

    console.log(`✓ Synchronized assets to ${port}/`);
  }

  console.log("✓ Core modules, test suites, and UI synchronized to all browser targets.");
}

sync().catch((err) => {
  console.error("Sync failed:", err);
  process.exit(1);
});
